importing some important lib

In [8]:
import tensorflow as tf
import mitdeeplearning as mld
import numpy as np
import matplotlib.pyplot as plt


In [10]:
sport=tf.constant("Tennis",tf.string)
number=tf.constant(1.234345343,tf.float64)
print("`sport` is a {}-d Tensor".format(tf.rank(sport).numpy))
print("`number`is a {}-d Tensor".format(tf.rank(number).numpy))

`sport` is a <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=0>>-d Tensor
`number`is a <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=0>>-d Tensor


vector and list can be used as 1-d tensor


In [13]:
sport1=tf.constant(["tennis","football"],tf.string)
number1=tf.constant([1.234444544,5.354457876,6.987868775765],tf.float32)
print("`sport1` is a {}-d Tensor".format(tf.rank(sport1).numpy))
print("`number1`is a {}-d Tensor".format(tf.rank(number1).numpy))


`sport1` is a <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=1>>-d Tensor
`number1`is a <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=1>>-d Tensor


In [18]:
matrix=tf.constant([[1,2,3],[1,2,3],[1,2,3]],tf.int64)
# print("`matrix`is a {}-d Tensor".format(tf.rank(matrix).numpy))
assert isinstance(matrix,tf.Tensor)
assert tf.rank(matrix).numpy()==2


In [25]:
# creating 4-D also known as rank-4 tensor
image=tf.zeros([10,256,256,3])
assert isinstance(image,tf.Tensor)
assert tf.rank(image).numpy()==4
assert tf.shape(image).numpy().tolist()==[10,256,256,3]


In [27]:
row_vector=matrix[1]
col_vector=matrix[:1]
scalar=matrix[0,1]
print("row_vector".format(row_vector.numpy()))
print("col_vector".format(col_vector.numpy()))
print("scalar".format(scalar.numpy()))
print(scalar)

row_vector
col_vector
scalar
tf.Tensor(2, shape=(), dtype=int64)


In [28]:
# compuation on Tensor
# crate the node and initialize values
a=tf.constant(12)
b=tf.constant(39)
c1=tf.add(a,b)
c2=a+b
print(c1)
print(c2)

tf.Tensor(51, shape=(), dtype=int32)
tf.Tensor(51, shape=(), dtype=int32)


In [35]:

def fun(a,b):
    c=tf.add(a,b)
    d=tf.subtract(b,1)
    e=tf.multiply(c,d)
    return e
e_out=fun(10,4)
print(e_out)

tf.Tensor(42, shape=(), dtype=int32)
